version: "3"

services:
  frontend:
    image: ${{ secrets.DOCKERHUB_REPO }}:frontend
    container_name: frontend
    restart: always
    ports:
      - "4000:4000"
    networks:
      - mynetwork

  file_storage:
    image: ubuntu:latest
    container_name: file_storage
    restart: always
    volumes:
      - file_volume:/srv/file_storage/
    command: tail -f /dev/null
    networks:
      - mynetwork

volumes:
  file_volume:

networks:
  mynetwork:
    driver: bridge
